### ISSUE TITLE
Navigation Fragment

### ISSUE THREAD

**Issue by ferenczAndras** [byoutline/SecretSauce#3]
Hello.. Can you provide me an example, how do I have to set up the navgation fragment, to work properly ? I can't figure out. 
Thankyou.

**Comment by Naitbit** [comment]
Did you saw https://github.com/byoutline/SecretSauce/tree/feature/sample/sampleapplication ? 
`MainActivity` has drawer configured. 

SecretSauce drawer is intended for use cases where a lot of customization is required, if you just need "default" drawer NavigationView from design compat lib should work fine https://developer.android.com/reference/android/support/design/widget/NavigationView.html
